### TRAER TAREAS
GET http://localhost:3000/api/tasks

### CREAR TAREA
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "hola 1",
    "description": "hola",
    "poster": "www.google.com"
}

### MODIFICAR TAREA
PUT http://localhost:3000/api/tasks/2
Content-Type: application/json

{
    "title": "pppppp"
}

### ELIMINAR
DELETE http://localhost:3000/api/tasks/3